---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	researcher(researcher)
	researcher_tools(researcher_tools)
	compress_research(compress_research)
	__end__([<p>__end__</p>]):::last
	__start__ --> researcher;
	researcher -.-> researcher_tools;
	researcher_tools -.-> compress_research;
	researcher_tools -.-> researcher;
	compress_research --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
